version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: unless-stopped

  compiler:
    volumes:
    - ./dexer/app:/code
    build: ./dexer/
    ports:
    - "9009:8000"
    restart: unless-stopped
